create table if not exists public.scenarios (
  id text primary key,
  data jsonb not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.study_events (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  participant_id text not null,
  condition_order text,
  event_type text not null,
  screen text,
  scenario_id text,
  interface_label text,
  interface_type text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.study_submissions (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null default now(),
  participant_id text not null,
  condition_order text,
  background jsonb not null default '{}'::jsonb,
  preference_ranking jsonb not null default '[]'::jsonb,
  scenarios jsonb not null default '[]'::jsonb,
  satisfaction jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.scenarios enable row level security;
alter table public.study_events enable row level security;
alter table public.study_submissions enable row level security;

drop policy if exists "Public can read scenarios" on public.scenarios;
create policy "Public can read scenarios"
on public.scenarios for select
using (true);

drop policy if exists "Public can upsert scenarios" on public.scenarios;
create policy "Public can upsert scenarios"
on public.scenarios for all
using (true)
with check (true);

drop policy if exists "Public can insert study events" on public.study_events;
create policy "Public can insert study events"
on public.study_events for insert
with check (true);

drop policy if exists "Public can insert study submissions" on public.study_submissions;
create policy "Public can insert study submissions"
on public.study_submissions for insert
with check (true);
